manifest-version = 1

[component]
name = "example-py-edge-function-component"
version = "1.0.0"
category = "edge-function"
subcategory = "wasm-function"
description = "Example Python component for edge function"
documentation = "https://github.com/edgee-cloud/example-py-component"
repository = "https://github.com/edgee-cloud/example-py-component"
language = "Python"
wit-version = "1.0.0"

[component.build]
command = "uv sync && uv run componentize-py --wit-path .edgee/wit/ --world edge-function componentize component -o component.wasm"
output_path = "./component.wasm"

[component.settings.example]
title = "Example Config Field"
type = "string"

