manifest-version = 1

[component]
name = "example-py-data-collection-component"
version = "1.0.0"
category = "data-collection"
subcategory = "analytics"
description = "Example Python component for data collection"
documentation = "https://github.com/edgee-cloud/example-py-component"
repository = "https://github.com/edgee-cloud/example-py-component"
language = "Python"
wit-version = "1.0.0"

[component.build]
command = "uv sync && rm -rf edgee_world && uv run componentize-py --wit-path .edgee/wit/ bindings edgee_world && uv run componentize-py --wit-path .edgee/wit/ --world data-collection componentize component -o dc_component.wasm"
output_path = "./dc_component.wasm"

[component.settings.example]
title = "Example Config Field"
type = "string"

