[project]
name = "example-py-component"
version = "0.1.0"
description = "Edgee python3 example for implementation of a data collection component"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "componentize-py>=0.16.0",
]
