manifest-version = 1

[component]
name = "example-py-consent-management-component"
version = "1.0.0"
category = "consent-management"
subcategory = "consent-mapping"
description = "Example Python component for consent management"
documentation = "https://github.com/edgee-cloud/example-py-component"
repository = "https://github.com/edgee-cloud/example-py-component"
language = "Python"
wit-version = "1.0.0"

[component.build]
command = "uv sync && rm -rf edgee_world && uv run componentize-py --wit-path .edgee/wit/ bindings edgee_world && uv run componentize-py --wit-path .edgee/wit/ --world consent-management componentize cmp_component -o cmp_component.wasm"
output_path = "./cmp_component.wasm"

[component.settings.example]
title = "Example Config Field"
type = "string"

